# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Torrance",
  "email": "torans@overlook.net",
  "avatarImagePath": "torrance.png",
  "userType": "Default",
  "password": "shining"
}

###

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:5000/users/664fa87232cb9a34ac22fc32/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarImagePath"; filename="0f911d33c7173176d73433b8b015c328.jpg"
Content-Type: image/png

< C:\Users\setu7\Downloads\0f911d33c7173176d73433b8b015c328.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
